# Generated by Django 3.0.5 on 2020-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200425_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='hamburguesas', to='api.Ingrediente'),
        ),
    ]
